import type { Report } from "./types";

export function reportToMarkdown(r: Report): string {
  const lines: string[] = [];
  lines.push(`# Data Quality IQ — ${r.dataset_name}`);
  lines.push("");
  lines.push(`**Data Integrity:** ${r.integrity_score}/100 (Grade ${r.integrity_grade}, confidence: ${r.integrity_confidence})`);
  lines.push(`**Model Readiness:** ${r.readiness_score}/100 (Grade ${r.readiness_grade}, confidence: ${r.readiness_confidence})`);
  lines.push(`**Overall:** ${r.overall_score}/100 (Grade ${r.overall_grade}, confidence: ${r.overall_confidence})`);
  lines.push(`**Verdict:** ${r.verdict}`);
  lines.push(`**Dataset Type:** ${r.dataset_type}`);
  lines.push(`**Dataset Purpose:** ${r.dataset_purpose}`);
  lines.push(`**Rows:** ${r.n_rows.toLocaleString()} | **Columns:** ${r.n_cols}`);
  if (r.target_column) lines.push(`**Target:** \`${r.target_column}\``);
  if (r.sampled) lines.push(`_Analyzed a sample of ${r.n_rows_analyzed.toLocaleString()} rows._`);
  lines.push("");
  lines.push(`## Executive Summary`);
  lines.push("");
  lines.push(r.exec_summary || "_No summary available._");
  lines.push("");

  if (r.recommendations?.length) {
    lines.push(`## Recommended Actions`);
    lines.push("");
    r.recommendations.forEach((rec, i) => lines.push(`${i + 1}. ${rec}`));
    lines.push("");
  }

  lines.push(`## Findings (${r.findings.length})`);
  lines.push("");
  const sorted = [...r.findings].sort(
    (a, b) => severityRank(a.severity) - severityRank(b.severity),
  );
  for (const f of sorted) {
    lines.push(`### [${f.severity.toUpperCase()}] ${f.title}`);
    if (f.column) lines.push(`- **Column:** \`${f.column}\``);
    lines.push(`- **Detail:** ${f.detail}`);
    lines.push(`- **Why it matters:** ${f.impact}`);
    if (f.fix_snippet) {
      lines.push("");
      lines.push("```python");
      lines.push(f.fix_snippet);
      lines.push("```");
    }
    lines.push("");
  }

  lines.push("---");
  lines.push(`_Generated by Data Quality IQ${r.ai_available ? "" : " (deterministic mode)"} at ${r.generated_at}_`);
  return lines.join("\n");
}

function severityRank(s: string): number {
  return ["critical", "high", "medium", "low", "info"].indexOf(s);
}

export function downloadMarkdown(r: Report) {
  const md = reportToMarkdown(r);
  const blob = new Blob([md], { type: "text/markdown" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `dataquality-iq-${r.dataset_name.replace(/[^a-z0-9]+/gi, "-").toLowerCase()}.md`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
